jobs:
    - command: cd data_prep/wham/scripts && 
        python create_wham_from_scratch.py 
          --wsj0-root ${DATA_DIRECTORY}/wsj0/
          --wham-noise-root ${DATA_DIRECTORY}/wham/wham_noise
          --output-dir ${DATA_DIRECTORY}/wham/
      run_in: host