jobs:
- command: curl https://storage.googleapis.com/whisper-public/wham_noise.zip 
      -o ${DATA_DIRECTORY}/wham_noise.zip
  name: download

- command: mkdir -p ${DATA_DIRECTORY}/wham/
  name: create_dir
  depends_on: download

- command: unzip ${DATA_DIRECTORY}/wham_noise.zip 
    -d ${DATA_DIRECTORY}/wham/wham-noise
  name: unzip
  depends_on: create_dir

- command: cd data_prep/wham/scripts && 
    python create_wham_from_scratch.py 
      --wsj0-root ${DATA_DIRECTORY}/wsj0/
      --wham-noise-root ${DATA_DIRECTORY}/wham/wham_noise
      --output-dir ${DATA_DIRECTORY}/wham/
  name: create_dataset
  depends_on: unzip