jobs:
    - command: curl https://storage.googleapis.com/whisper-public/wham_noise.zip 
        -o ${DATA_DIRECTORY}/wham_noise.zip
      run_in: host
    - command: mkdir -p ${DATA_DIRECTORY}/wham/
      run_in: host
    - command: unzip ${DATA_DIRECTORY}/wham_noise.zip 
        -d ${DATA_DIRECTORY}/wham/wham-noise
      run_in: host