num_jobs: 2 # controls whether to run this sequentially or in parallel

jobs:
# Before doing anything, download the toy data the scripts below depend on.
- script: scripts/download_toy_data.py
  config: data_prep/download_toy_data.yml
  run_in: host
  blocking: true

# Mix an incoherent dataset with Scaper.
- script: scripts/mix_with_scaper.py
  config: data_prep/wsj/incoherent.yml
  run_in: container