---
jobs:
- input_path: ${DATA_DIRECTORY}/babymusdb/train
  output_path: ${DATA_DIRECTORY}/babymusdb/scaper/train
  org_func: split_folder_by_class
  use_symlink: true
  
- input_path: ${DATA_DIRECTORY}/babymusdb/test
  output_path: ${DATA_DIRECTORY}/babymusdb/scaper/test
  org_func: split_folder_by_class
  use_symlink: true