name: Build and push docs

on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest
    container: pseeth/nussl:latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Building docs
      run: |
        cd docs/code
        pip install -r requirements.txt --ignore-installed
        make github
        cd ../..
        git add .
        git commit -am "DOCS: updating documentation"
        git push origin master