name: Build and push docs

on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest
    container: pseeth/nussl:latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Building docs
        run: |
          cd docs/code
          pip install -r requirements.txt --ignore-installed
          make github
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -am "DOCS: updating documentation"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}